### PR TITLE
fix: internal cmds escape special chars

### LINKED ISSUE #139: Internal commands should use statements with parameters, or correctly escape values
Create and populate a table with a name that includes a single quote:

```
→  create table [asdf'asdf] (t text);
→  insert into [asdf'asdf] values ('x');
→  select * from [asdf'asdf];
T
x

→  .dump
...
Error: failed to execute SQL: SELECT SQL FROM sqlite_master WHERE TBL_NAME='asdf'asdf'
syntax error around L1:56: `asdf`
```

Internally, this is how the SQL command is built:

```go
fmt.Sprintf("SELECT SQL FROM sqlite_master WHERE TBL_NAME='%s'", tableName),
```

[File: internal/shellcmd/dump.go](https://github.com/libsql/libsql-shell-go/blob/main/internal/shellcmd/dump.go#L113)

### PR DESCRIPTION
**Pull request by douglasmdev**
## Related Issues

- Closes #139 

## Visual reference

Before:
```
→  create table [asdf'asdf] (t text);
→  insert into [asdf'asdf] values ('x');
→  .dump
...
Error: failed to execute SQL: SELECT SQL FROM sqlite_master WHERE TBL_NAME='asdf'asdf'
syntax error around L1:56: `asdf`
```

Now:

```
→  create table [asdf'asdf] (t text);
→  insert into [asdf'asdf] values ('test');
→  create table '8test' (t text);
→  insert into '8test' values ('t');
→  create table 't(e!s?t+' (t text);
→  insert into 't(e!s?t+' values ('t');
→  .dump
PRAGMA foreign_keys=OFF;
CREATE TABLE [asdf'asdf] (t text);
INSERT INTO 'asdf''asdf' VALUES ('test');
CREATE TABLE '8test' (t text);
INSERT INTO '8test' VALUES ('t');
CREATE TABLE 't(e!s?t+' (t text);
INSERT INTO 't(e!s?t+' VALUES ('t');
→  .schema
CREATE TABLE '8test' (t text)         
CREATE TABLE [asdf'asdf] (t text)     
CREATE TABLE 't(e!s?t+' (t text)
→  .tables
8test         
asdf'asdf     
t(e!s?t+ 
```

### CODE REVIEW

File: internal/db/utils.go [hunk 1]
```diff
@@ -24,3 +35,20 @@ func IsValidSqldUrl(uri string) (bool, string) {
 func EscapeSingleQuotes(value string) string {
 	return strings.Replace(value, "'", "''", -1)
 }
+
+func HasSpecialCharacter(value string) bool {
+	if StartsWithNumber(value) {
+		return true
+	}
+	for _, char := range specialCharacters {
```
Comment (WilsonNet) [inline internal/db/utils.go:43]: can't we transform the string into a Set, so we don't have to check for duplicates?

File: internal/db/utils.go [hunk 2]
```diff
@@ -24,3 +35,20 @@ func IsValidSqldUrl(uri string) (bool, string) {
...
+			return true
+		}
+	}
+	return false
+}
+
+func StartsWithNumber(value string) bool {
+	firstChar := rune(value[0])
+	return unicode.IsDigit(firstChar)
+}
```
Comment (athoscouto) [inline internal/db/utils.go:54]: Detecting special digits is hard since we can always miss something.
For instance, `+` would be a special character, and it isn't on your list.
I suggest doing the other way around, looking for characters we know we can use without escaping.

Something like:
```go
func NeedsEscaping(name string) bool {
	if len(name) == 0 {
		return false
	}
	for i, char := range name {
		if !unicode.IsLetter(char) && (i == 0 || !unicode.IsDigit(char)) {
			return false
		}
	}
	return true
}
```

In case it needs escaping, then you can wrap it around single quotes and escape any single quotes in the name.

**Review by athoscouto — CHANGES_REQUESTED** [review]

**Comment by athoscouto** [comment]
Feel free to move forward if somebody else approves it! I may be getting the problem/solution the wrong way.

File: internal/db/utils.go (hunk 2 above)
Comment (douglasmdev) [reply internal/db/utils.go]: I agree with solution, just had to adapt this `NeedsEscaping` a little to make it work. Thanks =)

Comment (douglasmdev) [reply internal/db/utils.go]: Just need to write some tests (gotta adapt some things)

File: internal/db/utils.go [hunk 3]
```diff
@@ -24,3 +25,23 @@ func IsValidSqldUrl(uri string) (bool, string) {
...
 }
+
+func startsWithNumber(name string) bool {
+	firstChar := rune(name[0])
+	return unicode.IsNumber(firstChar)
+}
+
+func NeedsEscaping(name string) bool {
+	if len(name) == 0 {
+		return false
```
Comment (athoscouto) [inline internal/db/utils.go:36]: Empty names need escaping

File: internal/shellcmd/dump.go [hunk 4]
```diff
@@ -76,7 +76,12 @@ func dumpTableRecords(tableRecordsStatementResult db.StatementResult, config *Db
 		if tableRecordsRowResult.Err != nil {
 			return tableRecordsRowResult.Err
 		}
-		insertStatement := "INSERT INTO " + tableName + " VALUES ("
+
+		var formattedTableName = db.EscapeSingleQuotes(tableName)
+		if db.NeedsEscaping(tableName) {
+			formattedTableName = "'" + formattedTableName + "'"
+		}
```
Comment (athoscouto) [inline internal/shellcmd/dump.go:83]: ⛏️: you only need to escape single quotes if the name needs escaping

**Review by athoscouto — APPROVED** [review]
