### PR TITLE
More help for .mode command

### LINKED ISSUE #97: `.mode` command has insuffient help
By @CodingDoug [here](https://github.com/chiselstrike/turso-cli/issues/441)

-----

I discovered `.mode` by running `.help`:

```
  .dump       Render database content as SQL
  .help       List of all available commands.
  .indexes    List indexes in a table or database
  .mode       Set output mode
  .quit       Exit this program
  .read       Execute commands from a file
  .schema     Show table schemas.
  .tables     List all existing tables in the database.
```

The problem is that it's entirely unclear how to use it.

```
→  .mode
Error: accepts 1 arg(s), received 0
```

There should be some way to get a list of modes and what they do.

The sqlite CLI has [documentation](https://www.sqlite.org/cli.html) (see section 5 "Changing Output Formats") about its `.mode` command, but it doesn't look at all the same.  None of their modes `list`, `quote`, or `line` are accepted.

```
→  .mode line
Error: unsupported mode
```

### PR DESCRIPTION
**Pull request by douglasmdev**
## Description

- If user provides either no argument for MODE or an invalid one, prints an error message showing the currently set mode and a list of valid ones
- if the user provides a valid argument for MODE, silently updates the current mode to the newly provided one

## Related Issues

- Closes #97

### CODE REVIEW

File: internal/shellcmd/mode.go [hunk 1]
```diff
@@ -2,20 +2,43 @@ package shellcmd
...
 		if !ok {
 			return fmt.Errorf("missing db connection")
 		}
+		currentMode := config.GetMode()
+		if len(args) == 0 {
+			return fmt.Errorf("No mode provided. Current mode is %s. Valid modes are %s", currentMode, validModes)
+		}
+		if !validArg(args[0], cmd.ValidArgs) {
+			return fmt.Errorf("Invalid mode. Current mode is %s. Valid modes are %s", currentMode, validModes)
+		}
```
Comment (luisfvieirasilva) [inline internal/shellcmd/mode.go:41]: No need to this `if`. Switch's `default` case is exactly this. You feel free to use the message that you this it's best

Comment (douglasmdev) [reply internal/shellcmd/mode.go:41]: True! Do we plan on supporting more modes soon? Might be a good idea to get rid of the switch statement in favor of something that scales better. Sqlite3 has like 14 modes.

**Review by luisfvieirasilva — APPROVED** [review]

File: internal/shellcmd/mode.go (hunk 1 above)
Comment (WilsonNet) [reply internal/shellcmd/mode.go]: I don't think you can get rid of that complexity, just move to another place. Golang switch statements are fine

Comment (WilsonNet) [reply internal/shellcmd/mode.go]: that is very readable the way it is right now so it is ok, we can abstract after it gets too cluttered

**Review by WilsonNet — APPROVED** [review]
