### PR TITLE
fix: add a way to cancel running queries in the shell

### LINKED ISSUE #90: No way to cancel a shell.RunShellLine call
I'm running `shell.RunShellLine` on the `turso` CLI and I can't cancel it once it beings execution.
Not even bashing ctrl/cmd + C makes it exit.

### PR DESCRIPTION
**Pull request by StefanoSaffran**
## Description

This PR aims to add a way to cancel running queries in the shell.

## Related Issues

- Closes #90 

## Visual reference

image

### CODE REVIEW

File: internal/shell/shell.go [hunk 1]
```diff
@@ -76,17 +80,20 @@ func NewShell(config ShellConfig, db *db.Db) (*Shell, error) {
...
 	}
 
+	signals := make(chan os.Signal, 1)
+	signal.Notify(signals, os.Interrupt, syscall.SIGTERM)
+
 	for !sh.state.interruptReadEvalPrintLoop {
+		go func() {
+			<-signals
+			sh.CancelQuery()
+		}()
```
Comment (luisfvieirasilva) [inline internal/shell/shell.go:96]: here you're creating one goroutine for every user entry. This means that, if I have:
```
> select 1;
> select 1;
> select 1;
> selec^C
```
We have 4 goroutines creates for the same porpoises.

Also, this code aims to catch SIGTERM, and that's similar to what we do for non-interactive run (a.k.a `--exec` flag). So, it's interesting to add this logic on the same function level that we that we do for `--exec` flag. That is, if we have the logic inside `RunShellLine`. We should have the same logic for interactive shell inside `RunShell`

Comment (StefanoSaffran) [reply internal/shell/shell.go]: Done, thanks!

File: internal/shell/shell.go [hunk 2]
```diff
@@ -200,6 +196,9 @@ func (sh *Shell) appendStatementPartAndExecuteIfFinished(statementPart string) {
 		sh.state.readline.SetPrompt(sh.promptFmt(promptNewStatement))
 		err := sh.db.ExecuteAndPrintStatements(completeStatement, sh.config.OutF, false, sh.state.printMode)
 		if err != nil {
+			if strings.Contains(err.Error(), "context canceled") {
+				err = &shellerrors.CancelQueryContextError{}
+			}
```
Comment (luisfvieirasilva) [inline internal/shell/shell.go:201]: We already have a place for checks like this. Right now we check for `"interactive transaction not allowed in HTTP queries"` inside `db.executeQuery`. Is there any reason to do this check here instead of putting it together with the one that we already have?
Putting it here will make `context canceled` be displayed when we use `--exec` flag

Comment (StefanoSaffran) [reply internal/shell/shell.go]: The `context canceled` error was not being caught there. So I added it here, but since we also need it when we use `--exec` flag, I move it to the return of `PrintStatementsResult`.

File: pkg/shell/shell.go [hunk 3]
```diff
@@ -56,6 +69,11 @@ func RunShellLine(config ShellConfig, line string) error {
 		return err
 	}
 
+	go func() {
+		<-signals
+		shellInstance.CancelQuery()
```
Comment (WilsonNet) [inline pkg/shell/shell.go:74]: is there a chance that the cancellation fails or at least take more time than expect? maybe in that case we should have something to communicate with the user

**Review by WilsonNet — APPROVED** [review]
looks good to me, just an observation
